include $(TOPDIR)/rules.mk

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=Relay Watch Team <maintainers@example.com>

LUCI_TITLE:=LuCI Support for Relay Watch
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +luci-base +relaywatch

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot entry point
