#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/sbin/relaywatchd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -f
	procd_set_param respawn 300 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	:
}

reload_service() {
	procd_send_signal relaywatchd
}

service_triggers() {
	procd_add_reload_trigger relaywatch wireless
}
